name: "Build & Deploy"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: v20.11.0
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: npm
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: package-lock.json
      - name: Install dependancies
        run: npm install
      - name: Build
        run: npm run build
      - name: FTP Deployment
        uses: airvzxf/ftp-deployment-action@latest
        with:
          # FTP Server.
          server: ftp.mosesmwape.icu
          # FTP User.
          user: github@mosesmwape.icu
          # FTP Password.
          password: '@icuzambia'
          # Local directory.
          local_dir: ./dist
          # Remote directory.
          remote_dir: ./
          
        
          
